version: '3'
services:
  backstage:
    image: backstage:latest
    environment:
      # This value must match the name of the postgres configuration block.
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      GITHUB_TOKEN: $GITHUB_TOKEN
      AUTH_GITHUB_CLIENT_ID: $AUTH_GITHUB_CLIENT_ID
      AUTH_GITHUB_CLIENT_SECRET: $AUTH_GITHUB_CLIENT_SECRET
    ports:
      - '7000:7000'

  db:
    image: postgres
    restart: always
    environment:
      # NOT RECOMMENDED for a production environment. Trusts all incomming
      # connections.
      POSTGRES_HOST_AUTH_METHOD: trust